version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - postgresql://habibi_lr4e_user:YTPtpV2inEUSoltvQkRd0xQR9Xoh8OWo@dpg-csgl6artq21c73ds9nc0-a.oregon-postgres.render.com/habibi_lr4e
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: habibi_lr4e
      POSTGRES_USER: habibi_lr4e_user
      POSTGRES_PASSWORD: YTPtpV2inEUSoltvQkRd0xQR9Xoh8OWo
    ports:
      - "5432:5432"
